HelloMVC6/HelloMVC6/Models/ErrorViewModel.cs
namespace HelloMVC6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HelloMVC6/HelloMVC6/Controllers/HomeController.cs
using HelloMVC6.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Diagnostics;

namespace HelloMVC6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMemoryCache cache;

        public HomeController(ILogger<HomeController> logger, IMemoryCache cache)
        {
            _logger = logger;
            this.cache = cache;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            cache.TryGetValue<int>("ultimoIdCreato", out var id);
            _logger.LogInformation($"Ultimo id generato: {id}");
            return View(id);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HelloMVC6/HelloMVC6/Controllers/StudentiController.cs
using Microsoft.Extensions.Caching.Memory;

namespace HelloMVC6.Controllers;

public class StudentiController : Controller
{
    private readonly IStudentsService studentsService;
    private readonly IMemoryCache cache;

    public StudentiController(IStudentsService studentsService, IMemoryCache cache)
    {
        this.studentsService = studentsService;
        this.cache = cache;
    }

    public IActionResult Index()
    {
        // return View(studentsService.GetStudents());
        return View(studentsService.GetStudentiIndexViewModel());
    }

    public IActionResult Details(int id)
    {
        return View(studentsService.GetStudent(id));
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(StudenteCreateViewModel studente)
    {
        var id = studentsService.CreateStudent(studente);
        cache.Set("ultimoIdCreato", id);
        // return RedirectToAction("Index");
        return RedirectToAction("Details", new {id = id});
    }

    public IActionResult Edit(int id)
    {
        return View(studentsService.GetStudent(id));
    }

    [HttpPost]
    public IActionResult Edit(Studente studente)
    {
        studentsService.UpdateStudent(studente);
        return RedirectToAction("Index");
    }
}

HelloMVC6/HelloMVC6/ViewComponents/MyViewComponent.cs
namespace HelloMVC6.ViewComponents;

public class MyViewComponent: ViewComponent
{
    private readonly IStudentsService studentsService;

    public MyViewComponent(IStudentsService studentsService)
    {
        this.studentsService = studentsService;
    }

    public Task<IViewComponentResult> InvokeAsync(int parametro)
    {
        var id = studentsService.UltimoIdGenerato();
        var studente = studentsService.GetStudent(id);

        return Task.FromResult<IViewComponentResult>(
            View("CorsoCore", studente));
    }
}

HelloMVC6/HelloMVC6/Views/Shared/Components/My/CorsoCore.cshtml
@model Studente
<h3> Corso .NET Core 6</h3>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">@Model.Nome @Model.Cognome</h5>
    <p class="card-text">@Model.Matricola</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

HelloMVC6/HelloMVC6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelloMVC6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelloMVC6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HelloMVC6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Studenti" asp-action="Index">Studenti</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HelloMVC6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HelloMVC6/HelloMVC6/Views/Studenti/Create.cshtml
@model HelloMVC6.Core.ViewModels.StudenteCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StudenteCreateViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cognome" class="control-label"></label>
                <input asp-for="Cognome" class="form-control" />
                <span asp-validation-for="Cognome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelloMVC6/HelloMVC6/Views/Studenti/Details.cshtml
@model HelloMVC6.Core.Models.Studente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Studente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cognome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cognome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricola)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricola)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

HelloMVC6/HelloMVC6/Views/Studenti/Edit.cshtml
@model HelloMVC6.Core.Models.Studente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Studente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="Id" hidden/>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cognome" class="control-label"></label>
                <input asp-for="Cognome" class="form-control" />
                <span asp-validation-for="Cognome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricola" class="control-label"></label>
                <input asp-for="Matricola" class="form-control" />
                <span asp-validation-for="Matricola" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelloMVC6/HelloMVC6/Views/Studenti/Index.cshtml
@model IEnumerable<StudentiIndexViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomeCompleto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MediaEsami)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricola)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeCompleto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MediaEsami)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricola)
            </td>
            <td>
                <a class="btn-primary btn-warning" asp-action="Edit" asp-route-id="@item.Id">Modifica</a>
                <a class="btn-primary btn-info" asp-action="Details" asp-route-id="@item.Id">Dettagli</a>
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>